name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data To First URL
        run: |
          curl -X POST "https://:VrsNYmYIS76f9uhOzcylaQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:p9mbdFeeQJi5Qu8s7D6RDw/streams/AQAAAHLyRxZS1U7uhNckEaMAiecAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data To Second URL
        run: |
          curl -X POST "https://:lAiIQfi5SAK2GmtjGGqhIQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:p9mbdFeeQJi5Qu8s7D6RDw/streams/AQAAALMgT0PQ2EkTrvDKTqITRBEAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

