name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data To First URL
        run: |
          curl -X POST "https://:NKB4miFqTRiAZFWFH30JHg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:p9mbdFeeQJi5Qu8s7D6RDw/streams/AQAAABAsIQrra0uVjabgc87GSIcAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data To Second URL
        run: |
          curl -X POST "https://:7OHB3IjMT76VyLs6oBQoXA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:p9mbdFeeQJi5Qu8s7D6RDw/streams/AQAAALWNvH-ze0dUsMUykkbO3dAAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data To Third URL
        run: |
          curl -X POST "https://:0jnSRdIZRFKdwaadrovlCg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:p9mbdFeeQJi5Qu8s7D6RDw/streams/AQAAAH_cbXsFXkSPlaXIUJfWX70AAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

